# Site settings
title: mbellier.github.io
email: 
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mbellier.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  mbellier

# Build settings
markdown: kramdown
permalink: pretty